version: '3.2'
services:
  db:
    image: mongo:3.4-jessie
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo_configdb
        target: /data/configdb
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:27018:27017"
  app:
    image: glosbio-api:latest
    build:
      context: ./Backend
      dockerfile: app.dockerfile
    volumes:
      - type: bind
        source: ./Backend
        target: /opt/app
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
        - db
    restart: on-failure

volumes:
  mongo_db:
  mongo_configdb:

