dist: xenial

language: python

python: "3.6"

addons:
  apt:
    sources:
    - ppa:mc3man/trusty-media
    packages:
    - ffmpeg

services: mongodb

env:
- APP_DIR=AlgorithmAnalyzer/Backend

before_install:
- cd $APP_DIR
- mongod --shardsvr &

install:
- pip install pipenv
- pipenv install

script:
- python -m unittest